CREATE TABLE IF NOT EXISTS exercise_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    normalized_name VARCHAR(255) NOT NULL UNIQUE,
    muscle_group VARCHAR(100) NOT NULL
);

INSERT INTO exercise_catalog (name, normalized_name, muscle_group) VALUES
    ('Bench Press', 'bench press', 'Chest'),
    ('Incline Dumbbell Press', 'incline dumbbell press', 'Chest'),
    ('Chest Fly', 'chest fly', 'Chest'),
    ('Push Up', 'push up', 'Chest'),
    ('Overhead Press', 'overhead press', 'Shoulders'),
    ('Lateral Raise', 'lateral raise', 'Shoulders'),
    ('Rear Delt Fly', 'rear delt fly', 'Shoulders'),
    ('Barbell Row', 'barbell row', 'Back'),
    ('Pull Up', 'pull up', 'Back'),
    ('Lat Pulldown', 'lat pulldown', 'Back'),
    ('Deadlift', 'deadlift', 'Back'),
    ('Seated Cable Row', 'seated cable row', 'Back'),
    ('Barbell Curl', 'barbell curl', 'Biceps'),
    ('Dumbbell Curl', 'dumbbell curl', 'Biceps'),
    ('Hammer Curl', 'hammer curl', 'Biceps'),
    ('Triceps Pushdown', 'triceps pushdown', 'Triceps'),
    ('Skull Crusher', 'skull crusher', 'Triceps'),
    ('Dips', 'dips', 'Triceps'),
    ('Squat', 'squat', 'Quadriceps'),
    ('Front Squat', 'front squat', 'Quadriceps'),
    ('Leg Press', 'leg press', 'Quadriceps'),
    ('Leg Extension', 'leg extension', 'Quadriceps'),
    ('Bulgarian Split Squat', 'bulgarian split squat', 'Quadriceps'),
    ('Romanian Deadlift', 'romanian deadlift', 'Hamstrings'),
    ('Leg Curl', 'leg curl', 'Hamstrings'),
    ('Hip Thrust', 'hip thrust', 'Glutes'),
    ('Glute Bridge', 'glute bridge', 'Glutes'),
    ('Calf Raise', 'calf raise', 'Calves'),
    ('Seated Calf Raise', 'seated calf raise', 'Calves'),
    ('Crunch', 'crunch', 'Core'),
    ('Hanging Leg Raise', 'hanging leg raise', 'Core'),
    ('Plank', 'plank', 'Core')
ON CONFLICT (normalized_name) DO NOTHING;

ALTER TABLE exercise
    ADD COLUMN IF NOT EXISTS catalog_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_exercise_catalog'
    ) THEN
        ALTER TABLE exercise
            ADD CONSTRAINT fk_exercise_catalog
            FOREIGN KEY (catalog_id) REFERENCES exercise_catalog (id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_exercise_catalog_id ON exercise (catalog_id);

UPDATE exercise e
SET catalog_id = ec.id,
    name = ec.name
FROM exercise_catalog ec
WHERE e.catalog_id IS NULL
  AND LOWER(TRIM(e.name)) = ec.normalized_name;
